// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANkT-OGOCHRfNmR1NJhp3zaUZI2FNzL9M',
    appId: '1:1023394220341:web:81cee05934dcf72a83647c',
    messagingSenderId: '1023394220341',
    projectId: 'attandanceapp-38858',
    authDomain: 'attandanceapp-38858.firebaseapp.com',
    storageBucket: 'attandanceapp-38858.firebasestorage.app',
    measurementId: 'G-V8CQERSC9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDaNZOvzt96ygP23lLxIvXpmerrI0Nv0g',
    appId: '1:1023394220341:android:a982809bab1f4b4983647c',
    messagingSenderId: '1023394220341',
    projectId: 'attandanceapp-38858',
    storageBucket: 'attandanceapp-38858.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCWru-BWSST8vP-0emE4RtnHQK27R4knA',
    appId: '1:1023394220341:ios:27429484c552bb5483647c',
    messagingSenderId: '1023394220341',
    projectId: 'attandanceapp-38858',
    storageBucket: 'attandanceapp-38858.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );
}
